version: '2.1'

services:
  mysql_db:
    image: percona
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - /home/mrpedro/Programming/2021-2-QA-AUTO-PYTHON-VKGROUP-N-Petaichuk/Final_project/mysql/mysql_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin -uroot -ppass ping -h mysql_db
      timeout: 1s
      retries: 30

  mock:
    build: ./vk_api_mock
    image: vk_api
    ports:
      - "9090:9090"

  myapp:
    image: myapp
    volumes:
      - /home/mrpedro/Programming/2021-2-QA-AUTO-PYTHON-VKGROUP-N-Petaichuk/Final_project/static:/tmp
    entrypoint: /app/myapp --config=/tmp/config.py
    ports:
      - "8000:8000"
    depends_on:
      mysql_db:
        condition: service_healthy
      mock:
        condition: service_started

  selenoid:
    image: selenoid/chrome:95.0
    volumes:
      - /home/mrpedro/Programming/2021-2-QA-AUTO-PYTHON-VKGROUP-N-Petaichuk/Final_project/static/selenoid_config:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["-conf", "/etc/selenoid/browsers.json"]
    ports:
      - "4444:4444"

networks:
  default:
    external: true
    name: app-network
